config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [:destroy]
  resources :lists, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:create]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(params_bookmark)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def params_bookmark
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @movie = Movie.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render 'new'
    end
  end

  def destroy
  @list = List.find(params[:id])
  @list.destroy
  redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmark_helper.rb
module BookmarkHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class='form-content'>
  <%= simple_form_for([@list, @bookmark]) do |f| %>
  <%= f.association :movie %>
  <%= f.input :comment %>
  <%= f.submit 'Add movie', class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80);">
  <div class="container">
    <h1>See any kind of movies</h1>
  </div>
</div>

<div class='list container pt-3'>
  <h5>My lists</h5>
  <div class='cards'>
      <% @lists.each do |list| %>
        <% if list.photo.attached? %>
          <div class="card-list p-4 m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key %>')">
            <%= link_to list.name, list_path(list) %>
          </div>
        <% else %>
          <div class="card-list p-4 m-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1572177191856-3cde618dee1f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=564&q=80')">
            <%= link_to list.name, list_path(list) %>
          </div>
        <% end %>
      <% end %>
  </div>
  <%= link_to "New List", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="text-center">New list</h1>

<%= simple_form_for(@list) do |f| %>
<%= f.input :name %>
<%= f.input :photo, as: :file %>
<%= f.submit "Submit your list", class: "btn btn-primary" %>
<% end %>

  <div class="text-center">
    <%= link_to "Back to Lists", lists_path, class: "btn btn-secondary mt-3" %>
  </div>

</div>

app/views/lists/show.html.erb
<div class='container p-3'>
  <h1 class='text-center'><%= @list.name %></h1>

  <div class="cards">
    <% @list.bookmarks.each do |bookmark| %>
        <div class="card">
          <img src='<%= bookmark.movie.poster_url%>' alt='' class='img-thumbnail'>
          <div class='card-body'>
            <h5 class='card-title'><%= bookmark.movie.title%></h5>
            <p class='card-text'><%= bookmark.movie.overview%></p>
            <p>
              <%= bookmark.comment %>
            </p>
            <%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" } %>
          </div>
        </div>
    <% end %>
  </div>

  <div class='form-content w-50'>
    <%= simple_form_for([@list, @bookmark]) do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit 'Add movie', class: 'btn btn-secondary' %>
    <% end %>
  </div>

</div>
<div class='container justify-content-center pt-3'>
  <%= link_to "Delete", list_path(@list), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-secondary'%>

  <%= link_to "Back to Lists", lists_path, class: 'btn btn-secondary' %>
</div>